### PR TITLE
readme: consistent structure & formatting

### PR DESCRIPTION
**Pull request by dgw**
Brings this README structurally in line with those of other Microsoft projects like VSCode and Monaco.

Reorganized and rewrote some instructions for clarity.

Several `edit -> commit -> push -> preview (on GitHub)` cycles went into this, and I'm pretty happy with how it is now. That said, I do expect to incorporate feedback before this is really ready.

### CODE REVIEW

**Comment by dgw** [comment]
Merge conflict resolved.

**Comment by dgw** [comment]
Does this need another rebase or something?

**Comment by danhellem** [comment]
Yeah, we re-did the entire readme a few weeks ago. That was before i saw this PR (sorry about that). Can you rebase and create a new PR?

**Comment by dgw** [comment]
I don't see anything to rebase onto in the `master` branch. The readme itself was last updated (663dcb65) a few weeks before my last rebase of this pull request.

It should be possible to just reopen and merge this with a few clicks. Am I missing something that prevents the easy way? After pulling `master` from this upstream repo, `git merge --no-ff beautify-readme` worked with no issues.

**Pull request closed without merging**
